"""Comprehensive Greater Bengaluru Road Network & Empirical Incident Data."""

from __future__ import annotations
from typing import Any, Dict, List
from backend.schemas.models import (
    CriticalAssetSchema,
    EdgeSchema,
    NodeSchema,
    ScenarioPreset,
    DisruptionInput,
)
from src.simulation.models import ODDemand

BANGALORE_METRO_NODES: List[NodeSchema] = [
    NodeSchema(
        id="Node_SilkBoard",
        latitude=12.9175,
        longitude=77.6238,
        node_type="junction",
        label="Silk Board Interchange",
        description="Crucial nexus connecting Hosur Rd, BTM, and Outer Ring Road.",
    ),
    NodeSchema(
        id="Node_ElectronicCity",
        latitude=12.8450,
        longitude=77.6600,
        node_type="zone",
        label="Electronic City Tech Zone",
        description="Southern IT employment centroid and expressway terminal.",
    ),
    NodeSchema(
        id="Node_SonyWorld",
        latitude=12.9360,
        longitude=77.6280,
        node_type="junction",
        label="Sony World Koramangala",
        description="High-density commercial junction & 2-lane bottleneck.",
    ),
    NodeSchema(
        id="Node_SarjapurAgara",
        latitude=12.9230,
        longitude=77.6480,
        node_type="junction",
        label="Agara / Sarjapur Junction",
        description="Major intersection connecting Koramangala, HSR, and Sarjapur.",
    ),
    NodeSchema(
        id="Node_BellandurORR",
        latitude=12.9260,
        longitude=77.6760,
        node_type="junction",
        label="Bellandur Outer Ring Road",
        description="Tech corridor near Bellandur Lake, prone to flash waterlogging.",
    ),
    NodeSchema(
        id="Node_Marathahalli",
        latitude=12.9560,
        longitude=77.7010,
        node_type="junction",
        label="Marathahalli Bridge Junction",
        description="Confluence of Old Airport Road and Outer Ring Road.",
    ),
    NodeSchema(
        id="Node_WhitefieldITPL",
        latitude=12.9860,
        longitude=77.7340,
        node_type="zone",
        label="Whitefield ITPL Tech Corridor",
        description="Major eastern technology park and commercial center.",
    ),
    NodeSchema(
        id="Node_DomlurFlyover",
        latitude=12.9610,
        longitude=77.6430,
        node_type="junction",
        label="Domlur Flyover & TTMC",
        description="Arterial flyover and major BMTC bus rapid transit terminal.",
    ),
    NodeSchema(
        id="Node_Indiranagar100ft",
        latitude=12.9784,
        longitude=77.6408,
        node_type="junction",
        label="100 Feet Road Indiranagar",
        description="Primary commercial arterial connecting Old Airport Rd to Old Madras Rd.",
    ),
    NodeSchema(
        id="Node_CMHRoad",
        latitude=12.9780,
        longitude=77.6320,
        node_type="junction",
        label="CMH Road Metro Corridor",
        description="High-density east-west corridor alongside Purple Line Metro.",
    ),
    NodeSchema(
        id="Node_TrinityCircle",
        latitude=12.9728,
        longitude=77.6186,
        node_type="junction",
        label="Trinity Circle / MG Road",
        description="CBD gateway linking Indiranagar and central shopping district.",
    ),
    NodeSchema(
        id="Node_AnilKumble",
        latitude=12.9754,
        longitude=77.6068,
        node_type="junction",
        label="Anil Kumble Circle (Brigade Rd)",
        description="Central commercial intersection at MG Road and Brigade Road.",
    ),
    NodeSchema(
        id="Node_Jayanagar4th",
        latitude=12.9298,
        longitude=77.5834,
        node_type="zone",
        label="Jayanagar 4th Block Complex",
        description="Southern commercial and residential district centroid.",
    ),
    NodeSchema(
        id="Node_SouthEndCircle",
        latitude=12.9380,
        longitude=77.5790,
        node_type="junction",
        label="South End Circle",
        description="Historic roundabout connecting Jayanagar and Basavanagudi.",
    ),
    NodeSchema(
        id="Node_HebbalFlyover",
        latitude=13.0358,
        longitude=77.5970,
        node_type="junction",
        label="Hebbal Flyover (Airport Junction)",
        description="Northern bottleneck connecting ORR, Bellary Rd, and Airport Expressway.",
    ),
    NodeSchema(
        id="Node_BallariRoad",
        latitude=13.0080,
        longitude=77.5870,
        node_type="junction",
        label="Ballari Road (Mekhri Circle)",
        description="High-speed arterial approach to central Bengaluru.",
    ),
    NodeSchema(
        id="Node_YeshwanthpurCircle",
        latitude=13.0238,
        longitude=77.5501,
        node_type="junction",
        label="Yeshwanthpur Circle / TTMC",
        description="Northwestern transit hub linking metro, bus, and railway station.",
    ),
    NodeSchema(
        id="Node_TumkurRoad",
        latitude=13.0450,
        longitude=77.5100,
        node_type="zone",
        label="Tumkur Road (Peenya Corridor)",
        description="Industrial and freight expressway gateway.",
    ),
    NodeSchema(
        id="Hospital_Manipal",
        latitude=12.9584,
        longitude=77.6489,
        node_type="critical_asset",
        label="Manipal Hospital (Old Airport Rd)",
        description="Level-1 regional emergency trauma & cardiac hospital.",
    ),
    NodeSchema(
        id="Hospital_StJohns",
        latitude=12.9345,
        longitude=77.6190,
        node_type="critical_asset",
        label="St. John's Medical College Hospital",
        description="Major tertiary emergency care facility in Koramangala.",
    ),
    NodeSchema(
        id="Hospital_NIMHANS",
        latitude=12.9405,
        longitude=77.5950,
        node_type="critical_asset",
        label="NIMHANS Neuro Trauma Center",
        description="Apex emergency neurosurgery and trauma care hospital.",
    ),
    NodeSchema(
        id="Hospital_Victoria",
        latitude=12.9628,
        longitude=77.5746,
        node_type="critical_asset",
        label="Victoria Hospital & BMCRI",
        description="Largest government tertiary emergency hospital in Karnataka.",
    ),
    NodeSchema(
        id="Hospital_Narayana",
        latitude=12.8180,
        longitude=77.6940,
        node_type="critical_asset",
        label="Narayana Health City",
        description="Apex cardiac & multi-speciality medical campus.",
    ),
]

BANGALORE_METRO_EDGES: List[EdgeSchema] = [
    EdgeSchema(
        id="Edge_SilkBoard_Hosur",
        source="Node_SilkBoard",
        target="Node_ElectronicCity",
        length_km=9.8,
        free_flow_speed_kmph=65.0,
        nominal_capacity_veh_per_hour=3800.0,
        road_class="primary_arterial",
        baseline_flow_veh_per_hour=2600.0,
        name="Hosur Road Elevated Highway (Silk Board to Electronic City)",
        coordinates=[
            [12.9175, 77.6238],
            [12.8900, 77.6400],
            [12.8650, 77.6520],
            [12.8450, 77.6600],
        ],
    ),
    EdgeSchema(
        id="Edge_ElectronicCity_SilkBoard",
        source="Node_ElectronicCity",
        target="Node_SilkBoard",
        length_km=9.8,
        free_flow_speed_kmph=65.0,
        nominal_capacity_veh_per_hour=3800.0,
        road_class="primary_arterial",
        baseline_flow_veh_per_hour=2400.0,
        name="Hosur Road Inbound Highway (Electronic City to Silk Board)",
        coordinates=[
            [12.8450, 77.6600],
            [12.8650, 77.6520],
            [12.8900, 77.6400],
            [12.9175, 77.6238],
        ],
    ),
    EdgeSchema(
        id="Edge_SilkBoard_SonyWorld",
        source="Node_SilkBoard",
        target="Node_SonyWorld",
        length_km=2.8,
        free_flow_speed_kmph=45.0,
        nominal_capacity_veh_per_hour=2200.0,
        road_class="arterial",
        baseline_flow_veh_per_hour=1650.0,
        name="Koramangala 100ft Road (Silk Board to Sony World)",
        coordinates=[
            [12.9175, 77.6238],
            [12.9250, 77.6245],
            [12.9360, 77.6280],
        ],
    ),
    EdgeSchema(
        id="Edge_SonyWorld_Sarjapur",
        source="Node_SonyWorld",
        target="Node_SarjapurAgara",
        length_km=2.5,
        free_flow_speed_kmph=40.0,
        nominal_capacity_veh_per_hour=1800.0,
        road_class="secondary",
        baseline_flow_veh_per_hour=1450.0,
        name="Koramangala 80ft Road to Agara / Sarjapur",
        coordinates=[
            [12.9360, 77.6280],
            [12.9290, 77.6370],
            [12.9230, 77.6480],
        ],
    ),
    EdgeSchema(
        id="Edge_Sarjapur_Bellandur",
        source="Node_SarjapurAgara",
        target="Node_BellandurORR",
        length_km=3.2,
        free_flow_speed_kmph=50.0,
        nominal_capacity_veh_per_hour=3200.0,
        road_class="primary_arterial",
        baseline_flow_veh_per_hour=2700.0,
        name="Outer Ring Road (Agara to Bellandur Tech Hub)",
        coordinates=[
            [12.9230, 77.6480],
            [12.9240, 77.6620],
            [12.9260, 77.6760],
        ],
    ),
    EdgeSchema(
        id="Edge_Bellandur_Marathahalli",
        source="Node_BellandurORR",
        target="Node_Marathahalli",
        length_km=4.6,
        free_flow_speed_kmph=55.0,
        nominal_capacity_veh_per_hour=3400.0,
        road_class="primary_arterial",
        baseline_flow_veh_per_hour=2950.0,
        name="Outer Ring Road (Bellandur to Marathahalli Bridge)",
        coordinates=[
            [12.9260, 77.6760],
            [12.9380, 77.6890],
            [12.9560, 77.7010],
        ],
    ),
    EdgeSchema(
        id="Edge_Marathahalli_ITPL",
        source="Node_Marathahalli",
        target="Node_WhitefieldITPL",
        length_km=5.1,
        free_flow_speed_kmph=45.0,
        nominal_capacity_veh_per_hour=2400.0,
        road_class="arterial",
        baseline_flow_veh_per_hour=1900.0,
        name="ITPL Main Road (Marathahalli to Whitefield ITPL)",
        coordinates=[
            [12.9560, 77.7010],
            [12.9690, 77.7180],
            [12.9860, 77.7340],
        ],
    ),
    EdgeSchema(
        id="Edge_Domlur_Manipal",
        source="Node_DomlurFlyover",
        target="Hospital_Manipal",
        length_km=1.2,
        free_flow_speed_kmph=45.0,
        nominal_capacity_veh_per_hour=2400.0,
        road_class="arterial",
        baseline_flow_veh_per_hour=1200.0,
        name="Old Airport Road Emergency Approach (Domlur to Manipal)",
        coordinates=[
            [12.9610, 77.6430],
            [12.9595, 77.6460],
            [12.9584, 77.6489],
        ],
    ),
    EdgeSchema(
        id="Edge_SonyWorld_Domlur",
        source="Node_SonyWorld",
        target="Node_DomlurFlyover",
        length_km=3.1,
        free_flow_speed_kmph=45.0,
        nominal_capacity_veh_per_hour=2200.0,
        road_class="arterial",
        baseline_flow_veh_per_hour=1750.0,
        name="Inner Ring Road (Koramangala to Domlur Flyover)",
        coordinates=[
            [12.9360, 77.6280],
            [12.9460, 77.6330],
            [12.9610, 77.6430],
        ],
    ),
    EdgeSchema(
        id="Edge_Domlur_Indiranagar100ft",
        source="Node_DomlurFlyover",
        target="Node_Indiranagar100ft",
        length_km=2.2,
        free_flow_speed_kmph=45.0,
        nominal_capacity_veh_per_hour=2100.0,
        road_class="arterial",
        baseline_flow_veh_per_hour=1400.0,
        name="100 Feet Road (Domlur to Indiranagar Hub)",
        coordinates=[
            [12.9610, 77.6430],
            [12.9700, 77.6415],
            [12.9784, 77.6408],
        ],
    ),
    EdgeSchema(
        id="Edge_Indiranagar100ft_CMH",
        source="Node_Indiranagar100ft",
        target="Node_CMHRoad",
        length_km=1.4,
        free_flow_speed_kmph=40.0,
        nominal_capacity_veh_per_hour=1600.0,
        road_class="collector",
        baseline_flow_veh_per_hour=1100.0,
        name="CMH Road Metro Corridor (100ft Rd to Metro Station)",
        coordinates=[
            [12.9784, 77.6408],
            [12.9780, 77.6360],
            [12.9780, 77.6320],
        ],
    ),
    EdgeSchema(
        id="Edge_CMH_Trinity",
        source="Node_CMHRoad",
        target="Node_TrinityCircle",
        length_km=1.8,
        free_flow_speed_kmph=45.0,
        nominal_capacity_veh_per_hour=2200.0,
        road_class="arterial",
        baseline_flow_veh_per_hour=1500.0,
        name="Old Madras / Trinity Approach (CMH Rd to Trinity Circle)",
        coordinates=[
            [12.9780, 77.6320],
            [12.9750, 77.6250],
            [12.9728, 77.6186],
        ],
    ),
    EdgeSchema(
        id="Edge_Trinity_AnilKumble",
        source="Node_TrinityCircle",
        target="Node_AnilKumble",
        length_km=1.5,
        free_flow_speed_kmph=40.0,
        nominal_capacity_veh_per_hour=2400.0,
        road_class="arterial",
        baseline_flow_veh_per_hour=1800.0,
        name="M.G. Road Boulevard (Trinity Circle to Anil Kumble Circle)",
        coordinates=[
            [12.9728, 77.6186],
            [12.9740, 77.6120],
            [12.9754, 77.6068],
        ],
    ),
    EdgeSchema(
        id="Edge_AnilKumble_Victoria",
        source="Node_AnilKumble",
        target="Hospital_Victoria",
        length_km=3.8,
        free_flow_speed_kmph=40.0,
        nominal_capacity_veh_per_hour=2200.0,
        road_class="arterial",
        baseline_flow_veh_per_hour=1600.0,
        name="Kasturba Road to Victoria Emergency Trauma Center",
        coordinates=[
            [12.9754, 77.6068],
            [12.9690, 77.5900],
            [12.9628, 77.5746],
        ],
    ),
    EdgeSchema(
        id="Edge_Jayanagar_SouthEnd",
        source="Node_Jayanagar4th",
        target="Node_SouthEndCircle",
        length_km=1.3,
        free_flow_speed_kmph=40.0,
        nominal_capacity_veh_per_hour=1800.0,
        road_class="collector",
        baseline_flow_veh_per_hour=1100.0,
        name="Jayanagar 4th Block Arterial to South End Circle",
        coordinates=[
            [12.9298, 77.5834],
            [12.9340, 77.5810],
            [12.9380, 77.5790],
        ],
    ),
    EdgeSchema(
        id="Edge_SouthEnd_NIMHANS",
        source="Node_SouthEndCircle",
        target="Hospital_NIMHANS",
        length_km=2.1,
        free_flow_speed_kmph=45.0,
        nominal_capacity_veh_per_hour=2000.0,
        road_class="arterial",
        baseline_flow_veh_per_hour=1300.0,
        name="Bannerghatta Road (South End Circle to NIMHANS Trauma)",
        coordinates=[
            [12.9380, 77.5790],
            [12.9390, 77.5870],
            [12.9405, 77.5950],
        ],
    ),
    EdgeSchema(
        id="Edge_NIMHANS_SilkBoard",
        source="Hospital_NIMHANS",
        target="Node_SilkBoard",
        length_km=4.2,
        free_flow_speed_kmph=50.0,
        nominal_capacity_veh_per_hour=2800.0,
        road_class="primary_arterial",
        baseline_flow_veh_per_hour=2100.0,
        name="Hosur Road (NIMHANS / Dairy Circle to Silk Board)",
        coordinates=[
            [12.9405, 77.5950],
            [12.9330, 77.6080],
            [12.9175, 77.6238],
        ],
    ),
    EdgeSchema(
        id="Edge_Hebbal_Ballari",
        source="Node_HebbalFlyover",
        target="Node_BallariRoad",
        length_km=3.4,
        free_flow_speed_kmph=60.0,
        nominal_capacity_veh_per_hour=3600.0,
        road_class="primary_arterial",
        baseline_flow_veh_per_hour=2800.0,
        name="Ballari Road Airport Corridor (Hebbal to Mekhri Circle)",
        coordinates=[
            [13.0358, 77.5970],
            [13.0220, 77.5910],
            [13.0080, 77.5870],
        ],
    ),
    EdgeSchema(
        id="Edge_Ballari_Trinity",
        source="Node_BallariRoad",
        target="Node_TrinityCircle",
        length_km=4.5,
        free_flow_speed_kmph=45.0,
        nominal_capacity_veh_per_hour=2600.0,
        road_class="arterial",
        baseline_flow_veh_per_hour=1900.0,
        name="Palace Road / MG Link (Mekhri Circle to Trinity Circle)",
        coordinates=[
            [13.0080, 77.5870],
            [12.9880, 77.5980],
            [12.9728, 77.6186],
        ],
    ),
    EdgeSchema(
        id="Edge_Hebbal_Yeshwanthpur",
        source="Node_HebbalFlyover",
        target="Node_YeshwanthpurCircle",
        length_km=5.6,
        free_flow_speed_kmph=55.0,
        nominal_capacity_veh_per_hour=3200.0,
        road_class="primary_arterial",
        baseline_flow_veh_per_hour=2300.0,
        name="Outer Ring Road North (Hebbal to Yeshwanthpur TTMC)",
        coordinates=[
            [13.0358, 77.5970],
            [13.0300, 77.5750],
            [13.0238, 77.5501],
        ],
    ),
    EdgeSchema(
        id="Edge_Yeshwanthpur_Tumkur",
        source="Node_YeshwanthpurCircle",
        target="Node_TumkurRoad",
        length_km=4.8,
        free_flow_speed_kmph=60.0,
        nominal_capacity_veh_per_hour=3600.0,
        road_class="primary_arterial",
        baseline_flow_veh_per_hour=2500.0,
        name="Tumkur Road Elevated Expressway (Yeshwanthpur to Peenya)",
        coordinates=[
            [13.0238, 77.5501],
            [13.0350, 77.5300],
            [13.0450, 77.5100],
        ],
    ),
    EdgeSchema(
        id="Edge_SonyWorld_StJohns",
        source="Node_SonyWorld",
        target="Hospital_StJohns",
        length_km=1.3,
        free_flow_speed_kmph=40.0,
        nominal_capacity_veh_per_hour=1800.0,
        road_class="collector",
        baseline_flow_veh_per_hour=950.0,
        name="St. John's Hospital Emergency Feeder from Koramangala",
        coordinates=[
            [12.9360, 77.6280],
            [12.9350, 77.6230],
            [12.9345, 77.6190],
        ],
    ),
    EdgeSchema(
        id="Edge_ElectronicCity_Narayana",
        source="Node_ElectronicCity",
        target="Hospital_Narayana",
        length_km=4.2,
        free_flow_speed_kmph=55.0,
        nominal_capacity_veh_per_hour=2400.0,
        road_class="arterial",
        baseline_flow_veh_per_hour=1100.0,
        name="Hosur Road to Narayana Health City Corridor",
        coordinates=[
            [12.8450, 77.6600],
            [12.8300, 77.6780],
            [12.8180, 77.6940],
        ],
    ),
]

BANGALORE_METRO_CRITICAL_ASSETS: List[CriticalAssetSchema] = [
    CriticalAssetSchema(
        id="manipal_trauma_center",
        node_id="Hospital_Manipal",
        asset_type="hospital",
        criticality_weight=2.5,
        name="Manipal City Hospital (Level-1 Trauma Center, Old Airport Rd)",
    ),
    CriticalAssetSchema(
        id="st_johns_hospital",
        node_id="Hospital_StJohns",
        asset_type="hospital",
        criticality_weight=2.2,
        name="St. John's Medical College Hospital (Koramangala)",
    ),
    CriticalAssetSchema(
        id="nimhans_trauma_center",
        node_id="Hospital_NIMHANS",
        asset_type="hospital",
        criticality_weight=2.4,
        name="NIMHANS Neuro Emergency Trauma Center (Hosur Rd)",
    ),
    CriticalAssetSchema(
        id="victoria_hospital",
        node_id="Hospital_Victoria",
        asset_type="hospital",
        criticality_weight=2.5,
        name="Victoria Hospital & BMCRI Apex Government Trauma Center",
    ),
    CriticalAssetSchema(
        id="narayana_health_city",
        node_id="Hospital_Narayana",
        asset_type="hospital",
        criticality_weight=2.0,
        name="Narayana Health City (Electronic City)",
    ),
]

BANGALORE_METRO_POIS: List[Dict[str, Any]] = [
    {"id": "poi_manipal", "name": "Manipal Hospital (Old Airport Rd)", "category": "hospital", "node_id": "Hospital_Manipal", "coordinates": [77.6489, 12.9584]},
    {"id": "poi_st_johns", "name": "St. John's Medical College Hospital", "category": "hospital", "node_id": "Hospital_StJohns", "coordinates": [77.6190, 12.9345]},
    {"id": "poi_nimhans", "name": "NIMHANS Neuro Trauma Center", "category": "hospital", "node_id": "Hospital_NIMHANS", "coordinates": [77.5950, 12.9405]},
    {"id": "poi_victoria", "name": "Victoria Hospital & BMCRI", "category": "hospital", "node_id": "Hospital_Victoria", "coordinates": [77.5746, 12.9628]},
    {"id": "poi_narayana", "name": "Narayana Health City", "category": "hospital", "node_id": "Hospital_Narayana", "coordinates": [77.6940, 12.8180]},
    {"id": "poi_silk_board", "name": "Silk Board Interchange", "category": "junction", "node_id": "Node_SilkBoard", "coordinates": [77.6238, 12.9175]},
    {"id": "poi_sony_world", "name": "Sony World Koramangala Hub", "category": "junction", "node_id": "Node_SonyWorld", "coordinates": [77.6280, 12.9360]},
    {"id": "poi_hebbal", "name": "Hebbal Outer Ring Road Flyover", "category": "junction", "node_id": "Node_HebbalFlyover", "coordinates": [77.5970, 13.0358]},
    {"id": "poi_whitefield", "name": "ITPL Whitefield Tech Corridor", "category": "tech_hub", "node_id": "Node_WhitefieldITPL", "coordinates": [77.7340, 12.9860]},
    {"id": "poi_electronic_city", "name": "Electronic City Tech Zone", "category": "tech_hub", "node_id": "Node_ElectronicCity", "coordinates": [77.6600, 12.8450]},
    {"id": "poi_yeshwanthpur", "name": "Yeshwanthpur TTMC Multimodal Hub", "category": "transit_hub", "node_id": "Node_YeshwanthpurCircle", "coordinates": [77.5501, 13.0238]},
]

BANGALORE_METRO_DEMANDS: List[ODDemand] = [
    ODDemand(
        id="OD_ElectronicCity_Manipal",
        origin="Node_ElectronicCity",
        destination="Hospital_Manipal",
        demand_veh_per_hour=1400.0,
        time_period="morning_peak",
    ),
    ODDemand(
        id="OD_ElectronicCity_Whitefield",
        origin="Node_ElectronicCity",
        destination="Node_WhitefieldITPL",
        demand_veh_per_hour=1200.0,
        time_period="morning_peak",
    ),
    ODDemand(
        id="OD_Jayanagar_Trinity",
        origin="Node_Jayanagar4th",
        destination="Node_TrinityCircle",
        demand_veh_per_hour=1100.0,
        time_period="morning_peak",
    ),
    ODDemand(
        id="OD_Hebbal_Victoria",
        origin="Node_HebbalFlyover",
        destination="Hospital_Victoria",
        demand_veh_per_hour=900.0,
        time_period="morning_peak",
    ),
    ODDemand(
        id="OD_Tumkur_SilkBoard",
        origin="Node_TumkurRoad",
        destination="Node_SilkBoard",
        demand_veh_per_hour=850.0,
        time_period="morning_peak",
    ),
]

BANGALORE_METRO_PRESETS: List[ScenarioPreset] = [
    ScenarioPreset(
        id="scenario_silk_board_collapse",
        name="Silk Board Elevated Flyover Structural Closure",
        description="Acute 100% shutdown of Silk Board Elevated Highway. Diverts 5,000+ veh/h onto BTM & Koramangala residential streets.",
        icon="alert-triangle",
        disruptions=[
            DisruptionInput(asset_id="Edge_SilkBoard_Hosur", disruption_type="closure", capacity_multiplier=0.0)
        ],
        recommended_mitigation_id="scenario_green_corridor_mitigation",
    ),
    ScenarioPreset(
        id="scenario_bellandur_flood",
        name="Monsoon Flash Flooding (Bellandur ORR & Sarjapur)",
        description="Heavy 60mm/hr monsoon downpour causes severe waterlogging, cutting Outer Ring Road capacity by 60%.",
        icon="cloud-rain",
        disruptions=[
            DisruptionInput(asset_id="Edge_Sarjapur_Bellandur", disruption_type="weather", capacity_multiplier=0.40),
            DisruptionInput(asset_id="Edge_Bellandur_Marathahalli", disruption_type="weather", capacity_multiplier=0.40),
        ],
    ),
    ScenarioPreset(
        id="scenario_hebbal_gridlock",
        name="Hebbal Airport Flyover Freight Gridlock",
        description="Multi-axle container breakdown on Hebbal Flyover blocks 2 of 3 lanes inbound to Bengaluru city.",
        icon="alert-octagon",
        disruptions=[
            DisruptionInput(asset_id="Edge_Hebbal_Ballari", disruption_type="closure", capacity_multiplier=0.35)
        ],
    ),
    ScenarioPreset(
        id="scenario_mg_road_construction",
        name="Namma Metro Line 6 Construction (MG Road & Trinity)",
        description="Barricaded arterial lanes reduce throughput by 50% along Trinity Circle & Anil Kumble Circle.",
        icon="cone",
        disruptions=[
            DisruptionInput(asset_id="Edge_Trinity_AnilKumble", disruption_type="construction", capacity_multiplier=0.50)
        ],
    ),
    ScenarioPreset(
        id="scenario_green_corridor_mitigation",
        name="Active Traffic Police Emergency Green Wave Mitigation",
        description="Traffic wardens establish dedicated priority green-waves for Manipal, Victoria, and NIMHANS ambulances.",
        icon="shield-check",
        disruptions=[],
    ),
]

